python inference.py \
--embed_pt  data/emb/reddit/V2.pt \
--meta_json data/emb/reddit/V2.json \
--ckpt output/reddit/<RUN_DIR>/epoch_<EPOCH>.pt \
--output_path output/reddit150_infer/ \
--dataset REDDIT \
--seen_train_limit 150 \
--unseen_train_limit 50 \
--hidden_layers 2 \
--inner_lr 1e-3 \
--eval_inner_epochs 1 \
--val_ratio 0.9 \
--score_threshold -1 \
--seed 42 \
--device cuda:0
