python inference.py \
--embed_pt  data/emb/prism/V2.pt \
--meta_json data/emb/prism/V2.json \
--ckpt output/prism/<RUN_DIR>/epoch_<EPOCH>.pt \
--dataset PRISM \
--seen_train_limit -1 \
--unseen_train_limit -1 \
--hidden_layers 2 \
--inner_lr 1e-3 \
--eval_inner_epochs 1 \
--val_ratio 0.9 \
--score_threshold -1 \
--seed 42 \
--device cuda:0
